import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — VentureReady.ai",
  description: "Legal disclaimers regarding AI-generated evaluations, limitations of liability, and user responsibilities.",
};

export default function DisclaimerPage() {
  return (
    <article>
      <h1 className="text-3xl font-bold text-white mb-2">Disclaimer</h1>
      <p className="text-stone-500 text-sm mb-10 pb-10 border-b border-stone-800">
        Last Updated: February 5, 2026
      </p>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">General Disclaimer</h2>
        <p className="text-stone-400 leading-relaxed">
          The information and services provided by VentureReady are for informational purposes only.
          By using our Services, you acknowledge and agree to the following disclaimers.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">No Investment Advice</h2>

        <h3 className="text-base font-semibold text-stone-200 mb-3">AI-Generated Evaluations</h3>
        <p className="text-stone-400 leading-relaxed mb-3">VentureReady provides AI-powered analysis of business documents. This service:</p>
        <ul className="list-disc list-inside text-stone-400 space-y-2 mb-6 ml-2">
          <li><strong className="text-stone-300">Is NOT investment advice:</strong> Our evaluations do not constitute recommendations to invest or not invest</li>
          <li><strong className="text-stone-300">Is NOT financial planning:</strong> We do not provide financial planning or advisory services</li>
          <li><strong className="text-stone-300">Is NOT a guarantee:</strong> Feedback does not guarantee funding success or business outcomes</li>
          <li><strong className="text-stone-300">Is automated:</strong> All evaluations are generated by artificial intelligence, not human experts</li>
        </ul>

        <h3 className="text-base font-semibold text-stone-200 mb-3">Consult Professionals</h3>
        <p className="text-stone-400 leading-relaxed mb-3">Before making business or investment decisions, consult with:</p>
        <ul className="list-disc list-inside text-stone-400 space-y-2 ml-2">
          <li>Licensed financial advisors</li>
          <li>Qualified attorneys</li>
          <li>Certified accountants</li>
          <li>Industry experts</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">No Legal Advice</h2>
        <ul className="list-disc list-inside text-stone-400 space-y-2 ml-2">
          <li>Our evaluations may reference legal structures or compliance</li>
          <li>This information is general in nature only</li>
          <li>Always consult a qualified attorney for legal matters</li>
          <li>We are not responsible for legal compliance of your business</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">Accuracy and Completeness</h2>

        <h3 className="text-base font-semibold text-stone-200 mb-3">AI Limitations</h3>
        <p className="text-stone-400 leading-relaxed mb-3">While we strive for accuracy, AI-generated content may:</p>
        <ul className="list-disc list-inside text-stone-400 space-y-2 mb-6 ml-2">
          <li>Contain errors or inaccuracies</li>
          <li>Become outdated</li>
          <li>Misinterpret uploaded documents</li>
          <li>Provide incomplete analysis</li>
          <li>Reflect biases in training data</li>
        </ul>

        <h3 className="text-base font-semibold text-stone-200 mb-3">No Warranty</h3>
        <p className="text-stone-400 leading-relaxed mb-3">We do not warrant that:</p>
        <ul className="list-disc list-inside text-stone-400 space-y-2 ml-2">
          <li>Evaluations are error-free</li>
          <li>Information is current or complete</li>
          <li>Analysis is suitable for your specific situation</li>
          <li>Results will meet your expectations</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">No Guarantee of Results</h2>
        <p className="text-stone-400 leading-relaxed mb-3">Using VentureReady does not guarantee:</p>
        <ul className="list-disc list-inside text-stone-400 space-y-2 ml-2">
          <li>Successful fundraising</li>
          <li>Investor interest</li>
          <li>Business success</li>
          <li>Specific outcomes or results</li>
          <li>Improvements in your business</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">Limitation of Liability</h2>
        <div className="bg-stone-900 rounded-xl p-5 border border-stone-800 mb-6">
          <p className="text-stone-400 text-sm leading-relaxed uppercase tracking-wide">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, VENTUREREADY IS NOT LIABLE FOR: BUSINESS
            DECISIONS MADE BASED ON OUR EVALUATIONS; LOST OPPORTUNITIES OR MISSED FUNDING ROUNDS;
            FINANCIAL LOSSES RESULTING FROM USE OF OUR SERVICES; CONSEQUENTIAL, INCIDENTAL, OR
            PUNITIVE DAMAGES; OR ACTIONS OF INVESTORS, PARTNERS, OR OTHER THIRD PARTIES.
          </p>
        </div>
        <p className="text-stone-400 leading-relaxed">
          <strong className="text-stone-300">Maximum Liability:</strong> Our total liability is
          limited to the amount you paid for our Services in the past 12 months.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">AI Technology Disclaimer</h2>

        <h3 className="text-base font-semibold text-stone-200 mb-3">Nature of AI</h3>
        <ul className="list-disc list-inside text-stone-400 space-y-2 mb-6 ml-2">
          <li>AI models can make mistakes</li>
          <li>Evaluations are based on pattern recognition and training data</li>
          <li>AI cannot replace human judgment and expertise</li>
          <li>Technology is constantly evolving and improving</li>
        </ul>

        <h3 className="text-base font-semibold text-stone-200 mb-3">No Human Review</h3>
        <p className="text-stone-400 leading-relaxed mb-3">Unless specifically stated otherwise:</p>
        <ul className="list-disc list-inside text-stone-400 space-y-2 ml-2">
          <li>Evaluations are generated entirely by AI</li>
          <li>There is no human expert review of your documents</li>
          <li>Feedback is algorithmic, not professional advice</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">User Responsibility</h2>
        <p className="text-stone-400 leading-relaxed mb-3">You are solely responsible for:</p>
        <ul className="list-disc list-inside text-stone-400 space-y-2 ml-2">
          <li>Evaluating the suitability of our feedback for your situation</li>
          <li>Verifying any information or recommendations</li>
          <li>Making your own independent business decisions</li>
          <li>Consulting appropriate professionals</li>
          <li>Complying with applicable laws and regulations</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">Testimonials and Results</h2>
        <p className="text-stone-400 leading-relaxed mb-3">
          Any testimonials, case studies, or success stories:
        </p>
        <ul className="list-disc list-inside text-stone-400 space-y-2 ml-2">
          <li>Represent individual experiences only</li>
          <li>Are not typical or guaranteed results</li>
          <li>May not reflect your experience</li>
          <li>Should not be relied upon as promises of specific outcomes</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">As-Is Provision</h2>
        <div className="bg-stone-900 rounded-xl p-5 border border-stone-800">
          <p className="text-stone-400 text-sm leading-relaxed uppercase tracking-wide">
            THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
            EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO: MERCHANTABILITY, FITNESS FOR
            A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY OR RELIABILITY, OR UNINTERRUPTED
            OR ERROR-FREE OPERATION.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">Indemnification</h2>
        <p className="text-stone-400 leading-relaxed">
          By using our Services, you agree to indemnify VentureReady against claims arising from
          your use of the Services, your violation of any terms or policies, your violation of
          third-party rights, and content you upload to our platform.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">Children</h2>
        <p className="text-stone-400 leading-relaxed">
          Our Services are not intended for individuals under 18 years of age or anyone unable
          to form binding contracts.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">Severability</h2>
        <p className="text-stone-400 leading-relaxed">
          If any provision of this Disclaimer is found unenforceable, the remaining provisions
          remain in full effect. The unenforceable provision will be modified to be enforceable
          while preserving the intent of the original provision.
        </p>
      </section>

      <section className="bg-stone-900 rounded-xl p-6 border border-stone-800">
        <h2 className="text-base font-semibold text-white mb-3">Contact Us</h2>
        <div className="space-y-1 text-sm text-stone-400">
          <p>
            Email:{" "}
            <a href="mailto:legal@ventureready.ai" className="text-emerald-400 hover:text-emerald-300 transition-colors">
              legal@ventureready.ai
            </a>
          </p>
          <p>
            Website:{" "}
            <a href="https://ventureready.ai" className="text-emerald-400 hover:text-emerald-300 transition-colors">
              ventureready.ai
            </a>
          </p>
        </div>
      </section>
    </article>
  );
}
